FROM nginx:1.26.3-alpine3.20-perl
COPY ./backend_api_mongodb/sslcert/server.crt	/etc/nginx/cert/www.social-site-demo.com.crt
COPY ./backend_api_mongodb/sslcert/server.key	/etc/nginx/cert/www.social-site-demo.com.key
COPY ./backend_api_mongodb/nginx/nginx.conf		/etc/nginx/nginx.conf
COPY ./frontend_svelte/build					/usr/share/nginx/html
