FROM nginx:1.26.3-alpine3.20-perl
COPY ./backend_nginx/nginx/nginx.conf		/etc/nginx/nginx.conf
COPY ./backend_nginx/nginx/logrotate		/etc/logrotate.d/nginx
COPY ./frontend_svelte/build				/usr/share/nginx/html
